#name: remote ssh command
#on: [push]
#jobs:

#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#    - name: Install SSH Key
#      uses: shimataro/ssh-key-action@v2
#      with:
#        key: ${{ secrets.SSH_PRIVATE_KEY }} 
#        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
#    - name: Adding Known Hosts
#      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
#    - name: Deploy with rsync
#      run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/voadragons/

name: remote ssh command
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        uses: contention/rsync-deployments@v1.0.0
        with:
         run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/voadragons
 
