name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Deploy with rsync
      run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/api-projeto-treinamento
