
name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          EXCLUDE: "/dist/, /home/voadragons/"

#name: remote ssh command
#on: [push]
#jobs:

#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#    - name: Install SSH Key
#      uses: shimataro/ssh-key-action@v2
#      with:
#        key: ${{ secrets.SSH_PRIVATE_KEY }} 
#        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
#    - name: Adding Known Hosts
#      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
#    - name: Deploy with rsync
#      run: rsync -av ../../api-projeto-treinamento ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/voadragons/

#name: remote ssh command
#2on: 
#  push:
#    branches: 
#      - main
  

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: rsync deployment
        # You may pin to the exact commit or the version.
        # uses: D3rHase/rsync-deploy-action@04c107c03c0c281c901e70eec58e22b56ea3d27a
#        uses: D3rHase/rsync-deploy-action@v0.1
#        with:
#          # hostname / IP of the server
#          HOST: ${{ secrets.SSH_HOST }}
#          # user of the server
#           #caiobraga/api-projeto-treinamento/.github/workflows/main.yml@refs/heads/main
#          REPOSITORY_PATH: ../../../../../../api-projeto-treinamento
#          USER: ${{ secrets.SSH_USER }}
#          # private ssh key registered on the server
#          PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SERVER_PATH: ./voadragons/
 

